### ISSUE TITLE
this class is not key value coding-compliant for the key bool.'  在Swift4.0运行demo要闪退 

### ISSUE THREAD

**Issue by SuperTreeGrove** [DeveloperJx/JXAutoEncoder#1]
2018-03-03 18:55:18.478310+0800 JXAutoEncoder[86717:10706586] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<JXAutoEncoder.ArchiverModel 0x6000000cf9d0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key bool.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001106a212b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010c9aef41 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001106a2079 -[NSException raise] + 9
	3   Foundation                          0x000000010c3cda63 -[NSObject(NSKeyValueCoding) setValue:forKey:] + 292
	4   JXAutoEncoder                       0x000000010c08e72a _T013JXAutoEncoderAACABSo7NSCoderC5coder_tcfc + 2042
	5   JXAutoEncoder                       0x000000010c091bc1 _T013JXAutoEncoder13ArchiverModelCACSo7NSCoderC5coder_tcfc + 1537
	6   JXAutoEncoder                       0x000000010c091c3f _T013JXAutoEncoder13ArchiverModelCACSo7NSCoderC5coder_tcfcTo + 47
	7   Foundation                          0x000000010c395510 _decodeObjectBinary + 2120
	8   Foundation                          0x000000010c394bc1 _decodeObject + 417
	9   Foundation                          0x000000010c4332bf +[NSKeyedUnarchiver unarchiveObjectWithFile:] + 148
	10  JXAutoEncoder                       0x000000010c090a6a _T013JXAutoEncoder13ArchiverModelC15decodedFromFileACyKFZ + 586
	11  JXAutoEncoder                       0x000000010c08bceb _T013JXAutoEncoder14ViewControllerC15buttonUnarchiveyypF + 123
	12  JXAutoEncoder                       0x000000010c08c9b8 _T013JXAutoEncoder14ViewControllerC15buttonUnarchiveyypFTo + 72
	13  UIKit                               0x000000010d24c972 -[UIApplication sendAction:to:from:forEvent:] + 83
	14  UIKit                               0x000000010d3cbc3c -[UIControl sendAction:to:forEvent:] + 67
	15  UIKit                               0x000000010d3cbf59 -[UIControl _sendActionsForEvents:withEvent:] + 450
	16  UIKit                               0x000000010d3cae86 -[UIControl touchesEnded:withEvent:] + 618
	17  UIKit                               0x000000010d2c2807 -[UIWindow _sendTouchesForEvent:] + 2807
	18  UIKit                               0x000000010d2c3f2a -[UIWindow sendEvent:] + 4124
	19  UIKit                               0x000000010d267365 -[UIApplication sendEvent:] + 352
	20  UIKit                               0x000000010dbb3a1d __dispatchPreprocessedEventFromEventQueue + 2809
	21  UIKit                               0x000000010dbb6672 __handleEventQueueInternal + 5957
	22  CoreFoundation                      0x0000000110645101 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	23  CoreFoundation                      0x00000001106e4f71 __CFRunLoopDoSource0 + 81
	24  CoreFoundation                      0x0000000110629a19 __CFRunLoopDoSources0 + 185
	25  CoreFoundation                      0x0000000110628fff __CFRunLoopRun + 1279
	26  CoreFoundation                      0x0000000110628889 CFRunLoopRunSpecific + 409
	27  GraphicsServices                    0x0000000112e2e9c6 GSEventRunModal + 62
	28  UIKit                               0x000000010d24b5d6 UIApplicationMain + 159
	29  JXAutoEncoder                       0x000000010c08f627 main + 55
	30  libdyld.dylib                       0x0000000111840d81 start + 1
)

**Comment by DeveloperJx** [comment]
由于swift 4.0提供了Codable协议，请使用Codable协议来实现相关逻辑，本类库在swift 4.0推出之后已停止维护，感谢您的使用与支持！
